Repository vinted/chef-proxysql, pull requests merged in 2018-06, with the labels that each got.

#32 Allow multiple interface declarations.
  libraries/proxysql_service.rb
Labels: 2.3.0

#34 Remove default proxysql service from package
  libraries/proxysql_service.rb
  test/integration/default/proxysql-defaults.rb
Labels: 2.3.1

#35 Extract statements into attributes
  README.md
  attributes/statements.rb
  libraries/proxysql_service.rb
Labels: 2.4.0

#36 Features/add post statements
  README.md
  attributes/statements.rb
  libraries/proxysql_service.rb
Labels: 2.4.0

#37 Remove constructed_service_name method
  libraries/proxysql_service.rb
Labels: 2.4.0

#39 Bump proxysql to 1.4.8
  README.md
  attributes/default.rb
Labels: 3.0.0

#40 Add proxysql_servers configuration support
  README.md
  attributes/default.rb
  attributes/statements.rb
  libraries/proxysql_service.rb
  templates/default/proxysql.cnf.erb
Labels: 3.1.0

#41 Add support for multiple admin_credentials
  libraries/proxysql_service.rb
  test/integration/2mysql/proxysql.rb
  test/integration/2mysql/service.rb
  test/integration/cookbooks/test-proxysql/recipes/2mysql.rb
Labels: 3.2.0

#42 Add config helper proxysql_servers
  libraries/proxysql_config_proxysql_servers.rb
Labels: 3.2.0
