Repository vinted/chef-proxysql, pull requests merged in 2018-04, with the labels that each got.

#24 Features/add lock version attribute
  .kitchen.yml
  attributes/default.rb
  libraries/proxysql_service.rb
Labels: 1.3.1

#18 Fixed template content
  templates/default/proxysql.cnf.erb
Labels: 1.3.1

#23 Add package_release attribute
  attributes/repository.rb
  libraries/proxysql_service.rb
Labels: BREAKING CHANGE

#21 Add proxysql_ prefix to BaseService class
  libraries/base_service.rb
  libraries/proxysql_admin_config.rb
  libraries/proxysql_service.rb
Labels: 2.0.0, BREAKING CHANGE

#25 Construct proxysql service name only from service_name attribute
  README.md
  libraries/proxysql_service.rb
  recipes/default.rb
  test/integration/cookbooks/test-proxysql/recipes/2mysql.rb
  test/integration/cookbooks/test-proxysql/recipes/default.rb
Labels: 2.0.0, BREAKING CHANGE

#26 Initialize local package_version variable when install proxysql package
  libraries/proxysql_service.rb
  metadata.rb
Labels: 2.0.1

#27 Bump ProxySQL version to 1.4.7
  README.md
  attributes/default.rb
Labels: 2.1.0
